version: '3.0'
 
services:
 nodejs: 
  build: .
  ports:
  - "8080:8080"
  - "3000:3000"
  links:
  - database  
 
 database:
  image: mongo:3.6.5
  ports:
  - "27017:27017" # specify port forwarding
